name: AutomaticDeploy

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - run: cat version.txt
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
