name: Create Pull Request for Release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: true
        type: choice
        default: "main"
        options:
          - main
          - staging
      target_branch:
        description: "Select the target branch the release branch will be merged into"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production


jobs:
  create-pr:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.source_branch }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem install --no-document git-pr-release
      - name: Create PR
        run: git-pr-release --squash
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ github.event.inputs.source_branch }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{github.event.inputs.target_branch}}
          GIT_PR_RELEASE_LABEL: "${{ github.event.inputs.target_branch }}-release"
          TZ: Asia/Tokyo