name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
      release_branch_name:
        description: "Select the release branch name to deploy"
        required: true         

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        if: ${{ github.event.inputs.environment == 'production' }}
        with:
          secret: ${{ github.TOKEN }}
          approvers: hkb3711220
          minimum-approvals: 1
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch_name }}
      - run: cat version.txt
      - run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}