name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - production
          - staging
      release_tag:
        description: "Select the release tag to deploy"
        required: true         

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}
      - run: echo "Deploying..."
