name: Linter

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7.2.1 # x-release-please-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_ALL_CODEBASE_TIMEOUT: 1000
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          DISABLE_ERRORS: true
