name: Pre-Review

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linter:
    uses: ./.github/workflows/linter.yaml
  
  scan:
    needs: linter
    uses: ./.github/workflows/scan.yaml

  post-message:
    needs: [linter, scan]
    uses: slackapi/slack-github-action@v2.0.0
    with:
      webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
      webhook-type: incoming-webhook
      payload: |
        text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        blocks:
          - type: "section"
            text:
              type: "mrkdwn"
              text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"