name: Pre-Review

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linter:
    uses: ./.github/workflows/linter.yaml
  
  scan:
    needs: linter
    uses: ./.github/workflows/scan.yaml
