name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Select the release tag to create a release branch"
        required: true
      target_branch:
        description: "Select the target branch the release branch will be merged into"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production


jobs:
  create-pr:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH: "release-${{ github.event.inputs.release_tag }}-${{ github.event.inputs.target_branch }}"
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.release_tag }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem install --no-document git-pr-release
      - name: Create Release Branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b ${{ env.RELEASE_BRANCH }} refs/tags/${{ github.event.inputs.release_tag }}
          git push origin ${{ env.RELEASE_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR
        run: git-pr-release --squash
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ env.RELEASE_BRANCH }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{github.event.inputs.target_branch}}
          GIT_PR_RELEASE_LABEL: "${{ github.event.inputs.target_branch }}-release"
          TZ: Asia/Tokyo
