name: Tag Staging

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0
      - name: Extract version from branch name
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          # Extract the version part after "release-"
          VERSION=${SOURCE_BRANCH#release-}
          # Set custom tag with -rc suffix
          echo "CUSTOM_TAG=${VERSION}-rc" >> $GITHUB_ENV
          
      - name: Tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
          RELEASE_BRANCHES: staging

